
/*
 *		Replace {INSTANCE_NAME} with such, like MSSQL12.SQLDEV_12
 *
 */

USE [master]
GO

/****** Object:  Database [fdb]    Script Date: 6/6/2019 8:43:53 PM ******/
CREATE DATABASE [fdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\{INSTANCE_NAME}\MSSQL\DATA\fdb.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'fdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\{INSTANCE_NAME}\MSSQL\DATA\fdb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [fdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fdb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [fdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fdb] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [fdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fdb] SET RECOVERY FULL 
GO

ALTER DATABASE [fdb] SET  MULTI_USER 
GO

ALTER DATABASE [fdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [fdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [fdb] SET  READ_WRITE 
GO
