
/*
 *		Replace {INSTANCE_NAME} with such, like MSSQL12.SQLDEV_12
 *
 */

USE [master]
GO

/****** Object:  Database [qdb]    Script Date: 6/6/2019 8:48:12 PM ******/
CREATE DATABASE [qdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'qdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\{INSTANCE_NAME}\MSSQL\DATA\qdb.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'qdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\{INSTANCE_NAME}\MSSQL\DATA\qdb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [qdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [qdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [qdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [qdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [qdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [qdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [qdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [qdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [qdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [qdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [qdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [qdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [qdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [qdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [qdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [qdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [qdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [qdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [qdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [qdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [qdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [qdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [qdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [qdb] SET RECOVERY FULL 
GO

ALTER DATABASE [qdb] SET  MULTI_USER 
GO

ALTER DATABASE [qdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [qdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [qdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [qdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [qdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [qdb] SET  READ_WRITE 
GO

